# **Feature Scaling & Normalization**

### **Scaling Methods:**
- 1. Z-score Standardization
- 2. Min-Max Scaling
### **Data Leakage Risk:**
- Applying scaling on both training and test data together leads to data leakage, as test data information is used during training.
### **When & Why to Scale:**
- Scale features when using distance-based models (KNN, SVM, PCA, Clustering).
- Avoid or handle carefully for tree-based models (Decision Trees, Random Forest), as they are insensitive to scale.
-------------------------

# 1. Import Libraries & Load Dataset

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [4]:
# load dataset
df = pd.read_csv("../datasets/telecom_churn.csv")

# display dataset
df.head()

,customer_id,signup_date,age,gender,city,education_level,employment_status,monthly_income,monthly_bill,internet_usage_gb,call_minutes,contract_type,support_tickets,customer_feedback,churn
0,10001,2019-01-01,65,Male,Multan,Bachelor,Employed,57643.0,10049.0,5.8,52.0,6-Month,1,Coverage is poor in my location,0
1,10002,2019-01-02,22,Female,Peshawar,Master,Employed,18207.0,2752.0,11.9,22.0,6-Month,2,Billing issues occurred multiple times,0
2,10003,2019-01-03,43,Male,Gujranwala,Secondary,Employed,13075.0,3155.0,40.0,87.0,Monthly,0,Billing issues occurred multiple times,0
3,10004,2019-01-04,21,Male,Lahore,Secondary,Employed,38890.0,5859.0,8.5,147.0,6-Month,2,Customer support was helpful,0
4,10005,2019-01-05,37,Female,Hyderabad,Primary,Employed,17475.0,5106.0,3.3,183.0,12-Month,0,Coverage is poor in my location,0

In [5]:
# Inspect Raw Values
df[["monthly_income", "monthly_bill"]].head()

   monthly_income  monthly_bill
0         57643.0       10049.0
1         18207.0        2752.0
2         13075.0        3155.0
3         38890.0        5859.0
4         17475.0        5106.0

In [6]:
# Why Scaling is Required
df[["monthly_income", "monthly_bill"]].describe()

       monthly_income  monthly_bill
count     1200.000000   1200.000000
mean     31155.975833   5939.150833
std      19351.937726   4046.473963
min       4984.000000    710.000000
25%      17795.000000   3291.750000
50%      26628.000000   4871.000000
75%      39886.250000   7485.500000
max     209790.000000  36361.000000

- Monthly income cause dominancy because values of monthly_income are very High.

# **1. Z-score Scaling Standardization Manual**
## 1.1: Calculate Mean & STD

In [10]:
income_mean = df["monthly_income"].mean()
income_std = df["monthly_income"].std()

print("Mean:", income_mean)
print("STD:", income_std)

Mean: 31155.975833333334
STD: 19351.937725889493

## 1.2: Apply Z-score Formula

In [12]:
df["income_zscore"] = (df["monthly_income"] - income_mean) / income_std

# display monthly_income and income_zscore
df[["monthly_income", "income_zscore"]].head()

   monthly_income  income_zscore
0         57643.0       1.368701
1         18207.0      -0.669131
2         13075.0      -0.934324
3         38890.0       0.399651
4         17475.0      -0.706956

In [14]:
# Verify Z-score scaling
df["income_zscore"].mean(), df["income_zscore"].std()

(np.float64(-1.628327102783563e-17), np.float64(0.9999999999999998))

# **2. Min-Max Scaling (map values: 0 to 1)**
## 2.1: Calculate Min & Max

In [15]:
bill_min = df["monthly_bill"].min()
bill_max = df["monthly_bill"].max()

print("Min:", bill_min)
print("Max:", bill_max)

Min: 710.0
Max: 36361.0

## 2.2: Apply Min-Max Formula

In [17]:
df["bill_min_max"] = (df["monthly_bill"] - bill_min) / (bill_max - bill_min)

# display monthy_bill & bill_min_max
df[["monthly_bill", "bill_min_max"]].head()

   monthly_bill  bill_min_max
0       10049.0      0.261956
1        2752.0      0.057277
2        3155.0      0.068582
3        5859.0      0.144428
4        5106.0      0.123306

In [18]:
# Verify Min-Max Scaling
df["bill_min_max"].min(), df["bill_min_max"].max()

(np.float64(0.0), np.float64(1.0))

# 3. Show Min, Max & Mid Values

In [21]:
df.loc[
    [df["monthly_bill"].idxmin(),
     df["monthly_bill"].idxmax(),
     df["monthly_bill"].sort_values().index[len(df)//2]],
    ["monthly_bill", "bill_min_max"]]

     monthly_bill  bill_min_max
893         710.0      0.000000
968       36361.0      1.000000
47         4873.0      0.116771

# 4. Side-by-Side Comparison

In [23]:
df[["monthly_income", "income_zscore", "monthly_bill", "bill_min_max"]].head()

   monthly_income  income_zscore  monthly_bill  bill_min_max
0         57643.0       1.368701       10049.0      0.261956
1         18207.0      -0.669131        2752.0      0.057277
2         13075.0      -0.934324        3155.0      0.068582
3         38890.0       0.399651        5859.0      0.144428
4         17475.0      -0.706956        5106.0      0.123306